# Generated by Django 5.2.1 on 2025-08-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=64, null=True)),
                ('coords', models.JSONField(blank=True, null=True)),
                ('address', models.JSONField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('reverse_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
